name: Check Time

on:
  workflow_dispatch:  # Позволяет запускать воркфлоу вручную

jobs:
  display_time:
    runs-on: ubuntu-latest

    steps:
      - name: Check current time
        run: |
          echo "Текущее время: $(date +%u) - $(date +%H)"
