name: GitHub Actions Demo
on: [pull_request]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install modules
        run: yarn install
      - name: Install Playwright Browsers
        run: npx playwright install chromium
      - name: build project
        run: yarn build
      - name: tests project
        run: yarn test-ct
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30