name: On pull request run

on:
    pull_request:
        types: [ opened ]

jobs:
  test-job:
    name: Main Step
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo -e "BLa-bla! - ${{github.event.workflow_run.conclusion}}"