name: Main

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed

jobs:
  test-job:
    name: Main Step
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo -e "main!"