name: Test

on:
  - pull_request

jobs:
  test-job:
    name: Test Step
    if: ${{ github.event.pull_request.user.login != 'FominDenis' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo -e "test!"